credential:
  client_id:
  client_secret:
app:
  session_secret:
  url: http://localhost:5000
server:
  port: 5000
  mode: "dev"
db:
  user: root
  password:
  dbname:
log:
  log_level: debug
  file_log_name: "./storages/logs/dev.001.log"
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true